### PR TITLE
fix: "iomem=relaxed" boot option for all platforms

### PR DESCRIPTION
**Pull request by hpersh**
Signed-off-by: Howard Persh <Howard_Persh@dell.com>

### CODE REVIEW

**Comment by theucke** [comment]
What is this fixing? Your message says it's a fix, but you don't say what is fixed, only what you did.

**Comment by hpersh** [comment]
Pull-request updated, HEAD is now 72c9ad85d1f30acc731d0a0447cd2548a3731070

**Review by heucke — COMMENTED** [review]
What is this fixing? Your commit message says it's a fix, but you don't say what is fixed, only what you did.

**Comment by hpersh** [comment]
Please look at the commit messge -- I added a link to the issue describing the problem.

**Comment by heucke** [comment]
I was referring to the subject of your commit message. You say how you fixed something, but not what you fixed or why. When I'm browsing the commit log for this repo, I'll just see `fix: "iomem=relaxed" boot option for all platforms`, but I won't know what the bug was. And if GitHub disappears, I'll never know.

**Review by heucke — APPROVED** [review]

**Pull request merged**
